### PR TITLE
Fix #268 error on dragging control point of arc

### LINKED ISSUE #268: Dragging control point of arc path will cause error
SVG Code:
```
<svg width="640" height="480" xmlns="http://www.w3.org/2000/svg">
 <g class="layer">
  <title>Layer 1</title>
  <path d="m187,194a114,62 0 1 0 219,2" fill="#FF0000" stroke="#000000" stroke-width="5"/>
 </g>
</svg>
```
image

1. Click "SVG" button
2. Paste the svg code to the textarea.
3. Click "OK" button
4. Click the arc path on the canvas
5. Click the arc path again
6. Drag the right-hand control point
7. The arc path disappeard and some errors displayed on console.

```
Error: <path> attribute d: Expected number, "M 187 194 A undefined undefi…".
Error: <path> attribute d: Expected number, "M 187 194 A NaN NaN NaN 0 0 …".
```

### PR DESCRIPTION
**Pull request by cuixiping**
Fixes #268

### CODE REVIEW

**Comment by brettz9** [comment]
Do you think you could manage adding a Testcafe UI test for this? It would be great for regression testing for new PRs to add their own UI tests (or unit tests for utilities)... See `/test/ui-tests/ui.js` for our only current (SVG-Edit-specific) UI test...  https://devexpress.github.io/testcafe/documentation/getting-started/ has some nice docs on how to do the tests...

**Comment by cuixiping** [comment]
I added a test case into `/test/ui-tests/ui.js`. You can take a look.

**Comment by cuixiping** [comment]
`svg-editor.html` can run well with Testcafe but `svg-editor-es.html` can not. 

Some errors were raised when I changed to `svg-editor-es.html` (in `/test/ui-tests/ui.js`).

```
fixture`TestCafe UI tests`
  .page` . . . . . . /svg-editor-es.html`;
```

**Comment by brettz9** [comment]
Awesome, thanks--will check it out... And yes, I think testcafe recently made a fix to an issue they were having with script tag imports as used in the "-es.html" file. This is great--hopefully a motivation for all of us to add ore such tests.

**Comment by cuixiping** [comment]
How to use locale(i18n) of svgedit in `/test/ui-tests/ui.js`?

Actually I should modify

    .click('#dialog_buttons > input[type=button][value=OK]')

to

    .click('#dialog_buttons > input[type=button][value=确定]')

before testing on my computer, since my default language is Chinese(zh-CN).

And I should change it back to English word ("OK") before commit.

**Comment by brettz9** [comment]
Maybe we could add some set-up and tear-down code to ensure the script changes the locale to English in the beginning (unless the tests are actually testing another locale), and then switches back to whatever the original locale was if these changes get saved in the testing browser.

**Comment by cuixiping** [comment]
good idea!

**Comment by brettz9** [comment]
Thanks very much for the PR and UI tests!

For UI tests, I've started abstracting out functions for some common testing needs (like opening the main menu), to make the tests simpler/more readable. I haven't yet added the `beforeEach`/`afterEach` [test hooks](https://devexpress.github.io/testcafe/documentation/test-api/test-code-structure.html#fixture-hooks) to reset the locale, but I hope to do that later.

Unfortunately, the testcafe improvements are not quite finished yet to allow `import` within script tags (see https://github.com/DevExpress/testcafe-hammerhead/issues/1725 ), but they did allow module scripts recently, so hopefully the former will be done as well.

In the future, please run `npm run browser-test` as well to do ESLint testing and to ensure the builds are made. It takes a little while though, so that's why testing on the modules file is usually easier until you are ready, though as you pointed out, we can't yet use the modules file for UI testing.

Best wishes and thanks again!

**Pull request merged**
