### PR TITLE
Feature/jsdoc

### PR DESCRIPTION
**Pull request by tetedacier**
Solve #240

### CODE REVIEW

**Comment by brettz9** [comment]
Very handy, thanks for getting this going! I think I found the rest of the ones that needed conversion to JSDoc, and it is passing... 

One issue if you happen to know how to fix--a file is getting generated within the docs (at least on my Mac), `module.html#.exports`, with the hash part of the file name (thus not working as a proper HTML file)...

**Comment by tetedacier** [comment]
I will give a look at it and submit a PR with most of document cleaned.
I known this PR was just the bootstrap of something bigger 😉

**Comment by tetedacier** [comment]
After some test this file seems to be a catch all for function/class defined directly in the export section.

The best solution to avoid this issue is to declare them outside of the export section. Note that at least [one bug of the jsdoc issues](https://github.com/jsdoc3/jsdoc/issues/1517) is related to this.

If this solution is ok for you, I will update those place where definition are done in export section.

**Comment by brettz9** [comment]
Ok, I think that's a pretty small price to pay for working docs... That'd be nice, thanks!

**Comment by tetedacier** [comment]
You're welcome, I'm on it.

**Pull request merged**
