### PR TITLE
Implement horizontal or vertical distribution alignment

### PR DESCRIPTION
**Pull request by mulder3062**
## PR description

First of all, thank you for creating and sharing the editor.
I needed horizontal or vertical distributive alignment and so I implemented it.

I made it work well in relative to 'page' and 'selected'.
Distributive alignment has no meaning in the 'smallest' and 'largest'. In this case, it operates as 'selected'.

## Checklist

Note that we require UI tests to ensure that the added feature will not be
nixed by some future fix and that there is at least some test-as-documentation
to indicate how the fix or enhancement is expected to behave.

- [x] - Added Cypress UI tests
- [X] - Ran `npm test`, ensuring linting passes and that Cypress UI tests keep
        coverage to at least the same percent (reflected in the coverage badge
        that should be updated after the tests run)
- [X] - Added any user documentation. Though not required, this can be a big
        help both for future users and for the PR reviewer.

## screenshot
*screenshot*
image

*animation*
animation_2

### CODE REVIEW

**Review by jfhenon — CHANGES_REQUESTED** [review]
Thank you for the PR, 
- Would you please review the svg icons to better match the added feature. What you do is more a distribution of spacing. 
- Can you add a cypress test as well?

**Comment by jfhenon** [comment]
Please also make sure that you pass npm run lint and npm run test locally (or using the CI on your PR).

**Comment by mulder3062** [comment]
lint and cypress test result.

```
$ npm run lint
> svgedit@7.1.3 lint
> standard .


$ npm run test
...
=============================== Coverage summary ===============================
Statements   : 61.15% ( 8215/13435 )
Branches     : 48.08% ( 3032/6306 )
Functions    : 63.43% ( 1058/1668 )
Lines        : 62.18% ( 7986/12843 )
================================================================================
```

**Comment by atensystem** [comment]
> Thank you for the PR,
> 
> * Would you please review the svg icons to better match the added feature. What you do is more a distribution of spacing.
> * Can you add a cypress test as well?

Improved with reference to Adobe tools.

**Review by jfhenon — APPROVED** [review]

**Pull request merged**
