### PR TITLE
#475  IAN as they changed the API, so removed IAN option in svg edit

### PR DESCRIPTION
**Pull request by AgriyaDev5**
## PR description

IAN as they changed the API, so removed IAN option in svg edit. The current extension is actually causing other issues. As SVG-Edit allow to import an image. I think it's not a big issue to choose and download an image on internet and to import it  after in SVG-Edit.

This extension is however needed for users that want to access quickly to a list of SVG that are related to an activity.

### CODE REVIEW

**Comment by q464pp** [comment]
可以拉取合併嗎 謝謝

**Comment by jfhenon** [comment]
I need to review this one before merging it.

**Review by q464pp — COMMENTED** [review]
審查什麼東西?

**Comment by jfhenon** [comment]
I didn't test if it is working correctly. 
I can put you as an approver if you have tested it.

**Comment by q464pp** [comment]
恩 謝謝

**Pull request merged**
