### PR TITLE
Fix undo on converting rectangle to path creating an exception

### PR DESCRIPTION
**Pull request by km384**
## PR description
 
 This is a bugfix for the issue mentioned at https://github.com/SVG-Edit/svgedit/issues/699

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#699: Undoing a convert to Path on a rectangle creates an exception](https://issuehunt.io/repos/21611548/issues/699)
---
</details>

### CODE REVIEW

**Review by jfhenon — CHANGES_REQUESTED** [review]
Great thank you. Could you also add the corresponding cypress test (I guess the easiest is to add this to one of the existing scenario).

**Comment by jfhenon** [comment]
Please also fix the lint issue.

**Comment by km384** [comment]
Oops, sorry about the latest https://github.com/SVG-Edit/svgedit/pull/703/commits/63654563be1340b18e352b2100bebf2b92d8bf32 commit, I will undo it and push a cleaner commit.

**Comment by km384** [comment]
The account which committed is my social account. This account is for formal uses. I apologize for any confusion caused.

**Review by jfhenon — APPROVED** [review]

**Comment by jfhenon** [comment]
@km384 not sure what need to be done for the issuehunt funding to be sent to you?

**Comment by km384** [comment]
I'm not sure either, try contacting customer support?

**Comment by jfhenon** [comment]
I think you need to go on their website and "declare" your PR but I'm not sure you can do it with a merged PR. I suggest you create a new PR (with just a minor modification, for example a comment) and then Submit the pull request via IssueHunt to receive this reward. Let me know if this doesn't work and we will contact their support.

**Pull request merged**
