### PR TITLE
Intersection list

### PR DESCRIPTION
**Pull request by codedread**
1) use getIntersectionList() when available (Opera, Chrome, Safari).
2) remove all suspendRedraws() - that API is removed in SVG 2

### CODE REVIEW

**Comment by progers** [comment]
This change looks great, just one minor comment nit.

Is this covered by a unittest? If so--does the test pass in both firefox and chrome?

**Comment by codedread** [comment]
This PR fixes Issue #36

**Comment by codedread** [comment]
"Is this covered by a unittest?" 

The sad answer is no - we never really wrote unit tests back in the early days of SVG-edit.  I only started when I began trying to disentangle all the code and split things out into modules.  I'd prefer to hold off on writing unit tests for svgcanvas since it's such a tangled mess still...

**Comment by progers** [comment]
And we're in!

**Pull request merged**
