### PR TITLE
Fix: Zoom selector rewrite

### PR DESCRIPTION
**Pull request by radasam**
## PR description

A full rewrite of the zoom selector in native js/css fixes issue #671 

Added tests for the zoom tool, under /cypress/e2e/unit/zoom.cy.js let me know if there is a more appropriate place for these.

## Checklist

Note that we require UI tests to ensure that the added feature will not be
nixed by some future fix and that there is at least some test-as-documentation
to indicate how the fix or enhancement is expected to behave.

- [x] - Added Cypress UI tests
- [x] - Ran `npm test`, ensuring linting passes and that Cypress UI tests keep
        coverage to at least the same percent (reflected in the coverage badge
        that should be updated after the tests run)
- [x] - Added any user documentation. Though not required, this can be a big
        help both for future users and for the PR reviewer.

### CODE REVIEW

**Comment by jfhenon** [comment]
I tested your work (https://deploy-preview-826--svgedit.netlify.app/editor/) and it's promising. 
Please fix a few things:
- Linter issues (we use standardjs) - use `npm run lint` and `npm run test `if you want to test your PR locally before pushing it to github.
- When you enter in the input field, you cannot type directly a number (I tried with 35...and you get 3.0)
- The list of choices should finish with % (100 -> 100%)
- The CSS for the background of the input field should be consistent with other (light gray)
image

**Review by jfhenon — CHANGES_REQUESTED** [review]
see discussions

**Comment by jfhenon** [comment]
I fixed the linter issues as well as the CSS.
Can you look at the remaining questions?

**Comment by radasam** [comment]
- Fixed the input issue - I've changed the behaviour so we now wait for the user to click off the input before triggering a zoom change.
- Suffixed each of the numerical values in the popup with %
- I've also changed the css slightly to align with the style of the other tools on the bottom panel

**Review by jfhenon — APPROVED** [review]

**Pull request merged**
