### PR TITLE
fixed bug of issue#364

### PR DESCRIPTION
**Pull request by fkcailiniyazi**
fixed bug of issue #364

### CODE REVIEW

**Comment by cuixiping** [comment]
You need not commit the `dist/*.*` and `*-iife.js` files.

**Comment by brettz9** [comment]
Yeah I guess since our Github Pages version is a separate repo, we need only have that repo include them (and I have just now updated that repo's .gitignore to avoid copying over some testing/coverage code which is I think not necessary to have online).

Feel free to add a commit to our regular svgedit repo to add `dist`, etc. to `gitignore` (though not to `.npmignore`), as the https://github.com/SVG-Edit/SVG-Edit.github.io fork will not copy each release's `.gitignore`; so as long as the `dist` files are built, they will be copied over and can be added to the repo when running the fork's copy script.

**Comment by brettz9** [comment]
And FWIW, at one point there were Git hosting libraries, so we could demo the latest on `master`, making inclusion of the `dist` files useful, but at this point, they are now apparently all offline.

**Comment by cuixiping** [comment]
Latest master demo should use source file only, not the built files on dist directory.

**Comment by brettz9** [comment]
It is nice to have some sanity checking to make sure the dist files are working, but I think such a change would be ok.

**Comment by jfhenon** [comment]
due to major upgrade to V7 - older issues/PR are closed.
You can open the same issues or create a PR based on V7

**Pull request closed without merging**
